# Generated by Django 4.0.6 on 2022-07-27 09:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('nsidc_app', '0018_alter_about_id_alter_informationresearch_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='myclass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slno', models.IntegerField()),
                ('tenderno', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=300)),
                ('releasedate', models.DateField(auto_now=True)),
                ('closingdate', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
