# Generated by Django 4.0.6 on 2022-07-27 09:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('nsidc_app', '0019_myclass'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myclass',
            name='closingdate',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='myclass',
            name='releasedate',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
